### ISSUE TITLE
Exceptions on script docstrings

### ISSUE THREAD

**Issue by RoyalTS** [terrencepreilly/darglint#139] opened 2020-11-18 10:53 UTC
I'm getting exceptions a la 

```
"""Functions to process the raw data."""
^
src/home_credit_default_risk/utils/misc/formatting.py:1:1: DAR000: Unexpected exception in darglint: Unsupported section type, Sections.VARIABLES_SECTION
```

when running the latest darglint release as a pre-commit hook using numpy style. The docstring being highlighted is not the docstring of a function but one at the top of a python script [as per D100/D104](http://www.pydocstyle.org/en/2.1.1/error_codes.html).

**Comment by terrencepreilly** [comment] 2020-12-20 15:15
Closing as a duplicate of Issue #133

**Closed by terrencepreilly** 2020-12-20 15:15 UTC
Labels: duplicate
