### ISSUE TITLE
Darglint fails when "except" contains multiple exceptions

### ISSUE THREAD

**Issue by mrietveld** [terrencepreilly/darglint#98] opened 2020-06-04 09:22 UTC
When the code contains the following (type of) line, darglint throws an error:

python code: 
```python
    except FileNotFoundError as fnfe:
        log.exception("File {} not found in package: {}".format(file_uri, pkg_name))
        raise fnfe
    except (KeyError, ModuleNotFoundError) as mnfe:
        log.exception("Package {} does not exist (trying to load: {})".format(pkg_name, "{}.{}".format(pkg_name, file_uri)))
          raise mnfe
```

The `except (KeyError, ModuleNotFoundError) as mnfe:` seems to be causing the problem. 

Error message:
```
ERROR:darglint:While getting ast.Attribute representation a node had an unexpected type Tuple
```

**Comment by terrencepreilly** [comment] 2020-06-06 05:24
This is a duplicate of Issue #97.  Thanks for the detailed bug report, though: it made it faster to fix.  Should be resolved when v1.4.1 is released.

**Closed by terrencepreilly** 2020-06-06 05:24 UTC
Labels: duplicate
