### ISSUE TITLE
Numpy convention

### ISSUE THREAD

**Issue by memery-imb** [terrencepreilly/darglint#59] opened 2019-12-04 22:17 UTC
Hey there, cool package!

I was wondering how difficult it would be to add a numpy docstring parser. Numpy docstrings are formatted similarly to Google docstrings. Is this something that I could help on?

**Comment by terrencepreilly** [comment] 2019-12-04 23:40
It shouldn't be too difficult to add new docstring conventions now.  It's definitely something you could help on, if you'd like.  Or, if you don't mind waiting, I could add it sometime this or next week.

If you'd like to give it a go, the grammars are defined in *darglint/parse/grammars*.  They're written in a dialect of BNF, and converted to a python class using the bnf_to_cnf utility in the *bin/* directory.  That class representing the grammar is used in the parsing algorithm.  (Feel free to ask any questions if any of that's confusing.)

**Comment by memery-imb** [comment] 2019-12-06 19:45
I was hoping to get to this today but I'm unable to and I'll at a conference next week. Sorry about this. :/

**Comment by terrencepreilly** [comment] 2019-12-12 03:07
I've added some unit tests for numpy format to the darglint/numpydoc branch, if you want to track progress.  I don't think it should take too long to implement.  It looks like this issue is a duplicate of Issue #14.  I'll just close them both once I've finished the initial implementation.

**Comment by terrencepreilly** [comment] 2020-03-07 18:34
It's not super stable, but I finished the initial implementation for Numpy docstrings.  If there are any edge cases which are missing, just let me know in the tracking issue, Issue #69.

**Closed by terrencepreilly** 2020-03-07 18:34 UTC
Labels: enhancement

**Comment by memery-imb** [comment] 2020-03-09 16:04
Will do!
